services:
  - type: web
    name: fastapi-pdf-translator
    runtime: python
    buildCommand: .venv/bin/pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10